spring:
  application:
    name: crypto-trading-system
  r2dbc:
    url: r2dbc:h2:mem:///tradingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

# Price feed client URLs (external APIs)
app:
  price-feed:
    binance:
      book-ticker-url: https://api.binance.com/api/v3/ticker/bookTicker
    huobi:
      tickers-url: https://api.huobi.pro/market/tickers
